# Generated by Django 4.1.3 on 2022-11-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='make',
            field=models.CharField(default='comapany', max_length=100),
            preserve_default=False,
        ),
    ]
